name: Run Tests on Matrix

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Pint
        run: ./vendor/bin/pint --test

      - name: Run Rector
        run: ./vendor/bin/rector process --dry-run

      - name: Run Tests
        run: ./vendor/bin/pest
